# Generated by Django 4.1.3 on 2022-11-12 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('ParticipateID', models.IntegerField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=255)),
                ('LastName', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('SubjectCode', models.IntegerField(primary_key=True, serialize=False)),
                ('SubjectName', models.CharField(max_length=20)),
                ('ParticipateID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computer_class_app.participants')),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('TeacherID', models.IntegerField(primary_key=True, serialize=False)),
                ('Firstname', models.CharField(max_length=255)),
                ('Lastname', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=30)),
                ('ParticipateID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computer_class_app.participants')),
                ('SubjectCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computer_class_app.subjects')),
            ],
        ),
        migrations.AddField(
            model_name='subjects',
            name='TeacherID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computer_class_app.teachers'),
        ),
        migrations.CreateModel(
            name='ProgessRecordBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('ParticipateID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computer_class_app.participants')),
                ('SubjectCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computer_class_app.subjects')),
                ('TeacherID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computer_class_app.teachers')),
            ],
        ),
    ]
