# Generated by Django 5.0.6 on 2024-07-02 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer_class_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progessrecordbook',
            name='ParticipateID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computer_class_app.participants'),
        ),
        migrations.AlterField(
            model_name='progessrecordbook',
            name='SubjectCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computer_class_app.subjects'),
        ),
        migrations.AlterField(
            model_name='progessrecordbook',
            name='TeacherID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computer_class_app.teachers'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='ParticipateID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computer_class_app.participants'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='TeacherID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computer_class_app.teachers'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='ParticipateID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computer_class_app.participants'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='SubjectCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computer_class_app.subjects'),
        ),
    ]
