# Generated by Django 5.0.6 on 2024-07-06 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computer_class_app', '0002_alter_progessrecordbook_participateid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='TeacherID',
        ),
    ]
