# Generated by Django 5.0.6 on 2024-07-06 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computer_class_app', '0003_remove_subjects_teacherid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participants',
            old_name='FirstName',
            new_name='Firstname',
        ),
        migrations.RenameField(
            model_name='participants',
            old_name='LastName',
            new_name='Lastname',
        ),
    ]
