# Generated by Django 5.0.6 on 2024-07-06 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computer_class_app', '0004_rename_firstname_participants_firstname_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='progessrecordbook',
            unique_together={('ParticipateID', 'TeacherID', 'SubjectCode')},
        ),
    ]
