# Generated by Django 5.0.6 on 2024-08-05 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computer_class_app', '0006_feedback'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feedback',
            new_name='Feedbacks',
        ),
    ]
